workout/__init__.py
from flask import Flask, request, render_template
from .config.variables import SECRET_KEY
from dotenv import dotenv_values
import os


# ENV = dotenv_values()
# print("ENV:", ENV) 



def create_app():
    app = Flask(__name__)

    # CONFIGS
    app.config["SECRET_KEY"] = SECRET_KEY





    from .views.workout_route import workblog
    app.register_blueprint(workblog)



        # CREATE AN ERROR ROUTE FOR 404 & 500

    # # 404 ERROR
    # @app.errorhandler(404)
    # def error_404(error):
    #     print("404 ERROR:", str(error))
    #     return render_template("error-404.html")
    
    #     # 500 ERROR
    # @app.errorhandler(Exception)
    # def error_500(error):
    #     print("500 ERROR:", str(error))
    #     return render_template("error-500.html")



    return app

workout/views/workout_route.py
from flask import Blueprint, request, flash, redirect, url_for, render_template, session, get_flashed_messages
# from workout.config.variables import SECRET_KEY
from ..config.database import get_connection
from werkzeug.security import generate_password_hash, check_password_hash

from ..config.database import get_connection
from workout.templates.utils.decorators import autheticated_admin, guest_admin, prevent_multiple







workblog = Blueprint("workblog", __name__)
# workblog.SECRET_KEY = SECRET_KEY 
workblog1 = []
workblog2 = []
db = get_connection()


# REGISTER ROUTE VIEW
@workblog.get("/register")
# @guest_admin
# @prevent_multiple
def register_page():
    return render_template("register.html")

# REGISTER ROUTE VIEW
@workblog.get("/login")
# @guest_admin
def login_page():
    return render_template("login.html")




@workblog.post("/create")
def handle_register_page():

    form = request.form

    email = form.get('email')
    name = form.get('name')
    password = form.get('password')
    hashed_password = generate_password_hash(password)

    if not db:
        flash("danger connecting to db", "danger")
        return redirect("/register")

    conn, cursor = db


    query = "INSERT INTO workout(name, email, password) VALUES(%s, %s, %s)"
    cursor.execute(query, [name, email, hashed_password])
    conn.commit()

    if not cursor.rowcount:
        flash("Failed to register admin", "danger")
        return redirect("/register")

    flash("Registration Successful", "Success")
    return redirect("/login")



# LOGIN ROUTE (VIEW)
@workblog.post("/login")
def handle_login_page():
    form = request.form

    # FORM FIELDS
    email = form.get("email")
    password = form.get("password")


    if not db:
        flash("danger connecting to db", "danger")
        return redirect("/login")
    
    conn, cursor = db


    # GET THE ADMIN
    query = "select * FROM workout WHERE email = %s"
    cursor.execute(query, [email])

    user = cursor.fetchone()

    if not user:
        flash("User does not exist", "danger")
        return redirect("/login")
    
    # VERIFY THE PASSWORD
    if not check_password_hash(user.get("password"), password):
        flash("Incorrect credentials", "danger")
        return redirect("/login")
    

    # CREATE MADMIN LOGIN SESSION
    session["WORKBLOG_LOGIN"] = user.get("id")

    flash("Login successful", "success")
    return redirect("/home")

# HANDLE ADMIN LOGOUT
@workblog.get("/logout")
def logout_admin():
    session.pop("WORKBLOG_LOGIN", None)
    return redirect("/login")


@workblog.get("/home")
# @autheticated_admin
def workblog_page():

    return render_template("index.html")
    # return redirect("/home")



@workblog.get("/data")
def workblog_data():
    html = render_template("all_workouts.html", workblog1=enumerate(workblog1))
    return html

@workblog.get("/edit")
def edit_workblog():
    return render_template("edit.html", workblog1=enumerate(workblog1))

@workblog.get("/workout")
def workout_page():
    return render_template("newworkout.html")

@workblog.get("/allworkout")
def allworkout_page():
    return render_template("all_workouts.html", workblog1=enumerate(workblog1))

@workblog.post("/add")
def workout_add():
    form = request.form
    workblog1.append(form)
    print("USERS:", workblog1)

    # for workblog in workouts

    return redirect("/data")

@workblog.get("/delete/<int:id>")
def workblog_delete(id):
    print("PRINT: ", len(workblog1))
    workblog1.pop(id)
    
    # Redirect to todo page
    return redirect(url_for('workblog.workblog_data'))

@workblog.post("/update/<int:id>")
def handle_save_workblog(id):
    # GET THE NEW VALUE FROM THE INPUT
    myForm = request.form
    print(myForm)
    
    workblog1[id] = myForm



    return redirect("/data")

workout/templates/all_workouts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Workouts</title>
    <link rel="shortcut icon" type="image/x-icon" href="static/admin/assets/img/favicon.ico">


    
</head>

<style>

    .animated-table {
        width: 80%;
        border-collapse: collapse;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
    }
    
    thead th, tbody td {
        padding: 10px;
        text-align: center;
    }
    
    thead th {
        background-color: #3498db;
        color: white;
        transition: background-color 0.3s;
    }
    
    tbody tr:nth-child(odd) {
        background-color: #f2f2f2;
    }
    
    tbody tr:hover {
        background-color: #3498db;
        color: white;
        transition: background-color 0.3s, color 0.3s;
    }
    
</style>

<!-- STYLE LINKS -->
<link rel="stylesheet" href="static/admin/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="static/admin/assets/css/animate.min.css">
<link rel="stylesheet" href="static/admin/assets/css/magnific-popup.css">
<link rel="stylesheet" href="static/admin/assets/fontawesome/css/all.min.css">
<link rel="stylesheet" href="static/admin/assets/css/dripicons.css">
<link rel="stylesheet" href="static/admin/assets/css/slick.css">
<link rel="stylesheet" href="static/admin/assets/css/default.css">
<link rel="stylesheet" href="static/admin/assets/css/meanmenu.css">
<link rel="stylesheet" href="static/admin/assets/css/style.css">
<link rel="stylesheet" href="static/admin/assets/css/responsive.css">

<body>
    <header class="header-area" style="background-color: black;">    
                
        <div id="header-sticky" class="menu-area menu-area2">
            <div class="container">
                <div class="second-menu">
                    <div class="row align-items-center">
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo2">
                                <a href="index.html"><img src="static/admin/assets/img/logo/w_logo.png" alt="logo"></a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6" style="align-items: center;">                               
                            <div class="main-menu text-right pr-15">
                                <nav id="mobile-menu">
                                    <ul>
                                        <li><a style="color: white;" href="{{ url_for('workblog.workblog_page') }}">Home</a></li>
                                        <li><a href="about.html" style="color: white;">About Us</a></li>
                                        
                                        <li class="has-sub"> 
                                            <a href="" style="color: white;">Join Now</a>
                                            <ul>													
                                                <li><a href="{{ url_for('workblog.logout_admin') }}">Log out</a></li>
                                            </ul>
                                        </li>               
                                    </ul>
                                </nav>
                            </div>
                        </div>    
                        <div class="col-xl-4 col-lg-4 d-none d-lg-block">
                            <div class="right-menu">
                                <ul>
                                    <li>
                                        <div class="menu-search text-right">
                                            <a href="#" data-toggle="modal" data-target=".popup1">
                                                <i class="fas fa-search"></i> 
                                            </a>
                                            <input type="text" placeholder="Enter Name">
                                        </div>
                                    </li> 
                                </ul>
                            
                            </div>
                        
                            
                            
                            
                        </div>
                        <div class="col-12">
                        <div class="mobile-menu"></div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main>
        <!-- slider-area -->
        <section id="parallax2" class="slider-area fix p-relative">
            <div class="slider-shape ss-two layer" data-depth="0.30"><div class="per-text"><h2>We Build<span>Champions</span></h2></div></div>
            
            <div class="slider-shape ss-six layer" data-depth="0.15"><img src="static/admin/assets/img/bg/heade-object.png" alt="shape"></div>
            <div class="slider-shape ss-eight layer" data-depth="0.50"><img src="static/admin/assets/img/bg/header-img.png" alt="shape"></div>
            <div class="slider-active2">
            <div class="single-slider slider-bg d-flex align-items-center" style="background-image:url(static/admin/assets/img/bg/header-bg.png); background-repeat: no-repeat; background-position: right;background-size: inherit;">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-lg-7">
                                <div class="slider-content s-slider-content text-left">

                            <div class="workblog_data">
                                <table class="animated-table">
                                    <thead>
                                        <tr>
                                            <th>S/N</th>
                                            <th>Number of push-ups</th>
                                            <th>Comments</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for index, workblog in workblog1 %}           
                                            <tr>
                                                <td>{{index + 1}}</td>
                                                <td>{{workblog["push-up nums"]}}</td>
                                                <td>{{workblog["comments"]}}</td>
                                                <td class="update" style="color: black;" ><a href="{{ url_for('workblog.workblog_delete', id=index) }}">Delete</a></td>
                                                <td class="update" style="color: black;"><a href="{{ url_for('workblog.edit_workblog') }}">Edit</a></td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>




</body>
</html>

workout/templates/newworkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Workout</title>
    <link rel="shortcut icon" type="image/x-icon" href="static/admin/assets/img/favicon.ico">


    
</head>
<style>
body{
    font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
}
.input-container {
    position: relative;
}

input[type="text"] {
    border: none;
    border-bottom: 2px solid #3498db;
    width: 300px;
    padding: 10px;
    font-size: 18px;
    transition: border-bottom 0.3s, width 0.3s;
    outline: none;
}

input[type="text"]:focus,
input[type="text"]:valid {
    border-bottom: 2px solid #2ecc71;
    width: 350px;
}

label {
    position: absolute;
    top: 0;
    left: 0;
    pointer-events: none;
    padding: 10px;
    transition: transform 0.3s, font-size 0.3s;
}

input[type="text"]:focus + label,
input[type="text"]:valid + label {
    transform: translateY(-25px);
    font-size: 14px;
    color: #2ecc71;
}

</style>

<!-- STYLE LINKS -->
<link rel="stylesheet" href="static/admin/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="static/admin/assets/css/animate.min.css">
<link rel="stylesheet" href="static/admin/assets/css/magnific-popup.css">
<link rel="stylesheet" href="static/admin/assets/fontawesome/css/all.min.css">
<link rel="stylesheet" href="static/admin/assets/css/dripicons.css">
<link rel="stylesheet" href="static/admin/assets/css/slick.css">
<link rel="stylesheet" href="static/admin/assets/css/default.css">
<link rel="stylesheet" href="static/admin/assets/css/meanmenu.css">
<link rel="stylesheet" href="static/admin/assets/css/style.css">
<link rel="stylesheet" href="static/admin/assets/css/responsive.css">

<body>
    <header class="header-area" style="background-color: black;">    
                
        <div id="header-sticky" class="menu-area menu-area2">
            <div class="container">
                <div class="second-menu">
                    <div class="row align-items-center">
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo2">
                                <a href="index.html"><img src="static/admin/assets/img/logo/w_logo.png" alt="logo"></a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6" style="align-items: center;">                               
                            <div class="main-menu text-right pr-15">
                                <nav id="mobile-menu">
                                    <ul>
                                        <li><a style="color: white;" href="{{ url_for('workblog.workblog_page') }}">Home</a></li>
                                        <li><a href="about.html" style="color: white;">About Us</a></li>
                                        
                                        <li class="has-sub"> 
                                            <a href="" style="color: white;">Join Now</a>
                                            <ul>													
                                                <li><a href="{{ url_for('workblog.logout_admin') }}">Log out</a></li>
                                            </ul>
                                        </li>               
                                    </ul>
                                </nav>
                            </div>
                        </div>    
                        <div class="col-xl-4 col-lg-4 d-none d-lg-block">
                            <div class="right-menu">
                                <ul>
                                    <li>
                                        <div class="menu-search text-right">
                                            <a href="#" data-toggle="modal" data-target=".popup1">
                                                <i class="fas fa-search"></i> 
                                            </a>
                                            <input type="text" placeholder="Enter Name">
                                        </div>
                                    </li> 
                                </ul>
                            
                            </div>
                        
                            
                            
                            
                        </div>
                        <div class="col-12">
                        <div class="mobile-menu"></div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main>
        <!-- slider-area -->
        <section id="parallax2" class="slider-area fix p-relative">
            <div class="slider-shape ss-two layer" data-depth="0.30"><div class="per-text"><h2>We Build<span>Champions</span></h2></div></div>
            
            <div class="slider-shape ss-six layer" data-depth="0.15"><img src="static/admin/assets/img/bg/heade-object.png" alt="shape"></div>
            <div class="slider-shape ss-eight layer" data-depth="0.50"><img src="static/admin/assets/img/bg/header-img.png" alt="shape"></div>
            <div class="slider-active2">
            <div class="single-slider slider-bg d-flex align-items-center" style="background-image:url(static/admin/assets/img/bg/header-bg.png); background-repeat: no-repeat; background-position: right;background-size: inherit;">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-lg-7">
                                <div class="slider-content s-slider-content text-left">

                                    <form action="/add" method="post">
                                        <div class="lastguy">
                                            <h2 >Did you workout today?</h2>
                                            <input type="radio" name="workout" id="" value="Yes" required>Yes
                                            <input type="radio" name="workout" id="" value="No" required>No
                                            <br>
                                            <br>
                                            
                                            <h4>push-ups</h4>
                                            <div class="input-container">
                                                <input type="text" id="animated-input" name="push-up nums" placeholder="Enter number of pushups done" required>
                                                
                                            </div>                                            <br>
                                            <br>

                                            <h4>Comments</h4>
                                            <input type="text" name="comments" style="width: 50%; border-radius: 6%;" placeholder="Enter Comments" required>
                                            <br>
                                            <br>
                                            

                                            <div class="slider-btn">                                          
                                                <!-- <a href="{{ url_for('workblog.workout_add')}}" class="btn ss-btn" data-animation="fadeInRight" data-delay=".8s">Add New Workouts</a> -->
                                                <button class="btn ss-btn" data-animation="fadeInRight" data-delay=".8s">Add New Workouts</button>
                                            </div>     
                                        </div>
                                    </form>


</body>
</html>

workout/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="static/admin/assets/img/favicon.ico">

    <title>Register</title>

    <link rel="stylesheet" href="static/admin/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/admin/assets/css/animate.min.css">
    <link rel="stylesheet" href="static/admin/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="static/admin/assets/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="static/admin/assets/css/dripicons.css">
    <link rel="stylesheet" href="static/admin/assets/css/slick.css">
    <link rel="stylesheet" href="static/admin/assets/css/default.css">
    <link rel="stylesheet" href="static/admin/assets/css/meanmenu.css">
    <link rel="stylesheet" href="static/admin/assets/css/style.css">
    <link rel="stylesheet" href="static/admin/assets/css/responsive.css">

</head>
<style> 
    body{
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        background: black;
    }
    .input-container {
        position: relative;
    }
    input[type="password"],
    input[type="text"] {
        border: none;
        border-bottom: 2px solid #3498db;
        width: 300px;
        padding: 10px;
        font-size: 18px;
        transition: border-bottom 0.3s, width 0.3s;
        outline: none;
    }
    input[type="password"]:focus,
    input[type="text"]:focus,
    input[type="text"]:focus {
        border-bottom: 2px solid #2ecc71;
        width: 350px;
    }
    
    label {
        position: absolute;
        top: 0;
        left: 0;
        pointer-events: none;
        padding: 10px;
        transition: transform 0.3s, font-size 0.3s;
    }
    input[type="password"]:focus + label,
    input[type="text"]:focus + label,
    input[type="text"]:focus + label {
        transform: translateY(-25px);
        font-size: 14px;
        color: #2ecc71;
    }
        .pluto{
            margin-top: 2%;
            height: 40vh;
            width: 50%;
            margin-left: 15%;
        }
        
    body{
        background-color: black;
        text-align: center;
    }
    .pluto{
        margin-top: 2%;
        height: 40vh;
        width: 50%;
        margin-left: 15%;
    }
</style>


<body>

    <header class="header-area" style="background-color: black;">    
                
            <div id="header-sticky" class="menu-area menu-area2">
                <div class="container">
                    <div class="second-menu">
                        <div class="row align-items-center">
                            <div class="col-xl-2 col-lg-2">
                                <div class="logo2">
                                    <a href="index.html"><img src="static/admin/assets/img/logo/w_logo.png" alt="logo"></a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6" style="align-items: center;">                               
                                <div class="main-menu text-right pr-15">
                                    <nav id="mobile-menu">
                                        <ul>
                                            <li><a href="about.html" style="color: white;">About Us</a></li>
                                            
                                            <li class="has-sub"> 
                                                <a href="" style="color: white;">Join Now</a>
                                                <ul>													
                                                    <li><a href="{{ url_for('workblog.login_page') }}">Log In</a></li>
                                                </ul>
                                            </li>               
                                        </ul>
                                    </nav>
                                </div>
                            </div>    
                            <div class="col-xl-4 col-lg-4 d-none d-lg-block">
                                <div class="right-menu">
                                    <ul>
                                        <li>
                                            <div class="menu-search text-right">
                                                <a href="#" data-toggle="modal" data-target=".popup1">
                                                    <i class="fas fa-search"></i> 
                                                </a>
                                                <input type="text" placeholder="Enter Name">
                                            </div>
                                        </li> 
                                    </ul>
                                
                                </div>
                                
                                
                                
                            </div>
                            <div class="col-12">
                            <div class="mobile-menu"></div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <main>
            <!-- slider-area -->
            <section id="parallax2" class="slider-area fix p-relative">
              
                <div class="slider-shape ss-two layer" data-depth="0.30"><div class="per-text"><h2>We Build<span>Champions</span></h2></div></div>
                
                <div class="slider-shape ss-six layer" data-depth="0.15"><img src="static/admin/assets/img/bg/heade-object.png" alt="shape"></div>
                <div class="slider-shape ss-eight layer" data-depth="0.50"><img src="static/admin/assets/img/bg/header-img.png" alt="shape"></div>
                <div class="slider-active2">
				<div class="single-slider slider-bg d-flex align-items-center" style="background-image:url(static/admin/assets/img/bg/header-bg.png); background-repeat: no-repeat; background-position: right;background-size: inherit;">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-lg-7">
                                    <div class="slider-content s-slider-content text-left">
                                        <div class="pluto">
                                            <h2>Register</h2>
                                            <form action="/create" method="post">
                                        
                                                <div class="input-container">
                                                    <input  type="text" name="name" placeholder="Enter your name" required>
                                                </div>
                                                <br>
                                                <div class="">
                                                    <input  placeholder="Enter your email" type="text" name="email" required>
                                                </div>
                                                <br>
                                                <div class="">
                                                    <input  placeholder="Enter your Password" type="password" name="password"  required>
                                                </div>
                                                <br>
                                                
                                                <div class="slider-btn">
                                                    <button  class="btn ss-btn" data-animation="fadeInRight" data-delay=".8s" >Register</button>
                                                </div>
                                            </form>
                                            </div>
                                    </div>
                                </div>
								<div class="col-lg-5">
									
								</div>
                            </div>
                        </div>
                    </div>
                    </div> 
</body>
</html>